#!/usr/bin/env python3
"""
A5 -- Revision-sensitivity analysis (NOT a controlled causal ablation; named
and interpreted as a sensitivity analysis throughout, per task spec).

Domain: Technology & AI (v0 -> v1, 76.7% -> 81.7%, the domain where the
coordinator's revision measurably helped).

Coordinator-model substitution note: the original coordinator is Claude
Sonnet via the Anthropic API. No ANTHROPIC_API_KEY is available in this
environment (only OPENAI_API_KEY, added earlier this session). Both
alternative revisions below are generated by gpt-5.6-sol instead. This is a
genuine confound -- differences from the original coordinator's v1 rubric
may reflect model-family differences, not just the evidence-visibility
manipulation this analysis is nominally testing. Disclosed here and must be
disclosed in the paper wherever these results are reported.

Step 1: Regenerate the v0-iteration disagreement cases for tech_ai's 20
original-corpus transcripts (single pass, v0 rubric, same 3 local judges,
temperature 0.0 -- deterministic, so this reproduces what iteration 1 of
the actual run would have produced, modulo any model drift since then).
These disagreement cases + per-model criterion quotes were not persisted
from the original run (confirmed during A4 recon), so this is how they are
recovered for use below.

Step 2: Generate two alternative rubric revisions via gpt-5.6-sol:
  (a) disagreement-informed -- sees the v0 rubric AND the disagreement
      cases/criterion quotes from Step 1, but NOT the original coordinator's
      specific revision text.
  (b) rubric-only -- sees ONLY the v0 rubric, no disagreement evidence at all.

Step 3: Run both alternative rubrics through the same 3-judge local panel on
the same 20 tech_ai transcripts (single pass each, no further iteration).

Step 4: Compare all conditions (v0, original coordinator v1, alt-a, alt-b)
on weighted agreement / Fleiss kappa / Gwet AC1.

Output: results/revision_sensitivity_analysis.json
"""
import csv
import json
from pathlib import Path

from openai import OpenAI

from judge_agent import judge_transcript, run_all_transcripts_one_model, merge_model_results
from experiment_utils import JudgeCallCache, fleiss_style_metrics, record_provenance

BASE = Path(__file__).resolve().parents[2]
REVIEW_QUEUE = BASE / "data" / "review_queue.csv"
V0_RUBRICS_PATH = BASE / "src" / "agents" / "rubrics.json"
FINAL_RUBRICS_PATH = BASE / "reports" / "rubric_calibration" / "calibrated_rubrics.json"
CALIBRATED_LABELS = BASE / "reports" / "rubric_calibration" / "calibrated_labels.csv"
RESULTS_DIR = BASE / "results"
CACHE_PATH = RESULTS_DIR / "judge_call_cache.csv"
OUT_PATH = RESULTS_DIR / "revision_sensitivity_analysis.json"

DOMAIN = "tech_ai"
JUDGE_MODELS = ["llama3.1:latest", "mistral:latest", "qwen2.5:7b"]
ALT_MODEL = "gpt-5.6-sol"


def load_env():
    env_path = BASE / ".env"
    if env_path.exists():
        import os
        for line in env_path.read_text().splitlines():
            if "=" in line and not line.startswith("#"):
                k, v = line.split("=", 1)
                os.environ.setdefault(k.strip(), v.strip())


def load_domain_transcripts() -> list:
    with open(REVIEW_QUEUE, encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    return [{"index": i, "transcript": r["transcript"]} for i, r in enumerate(rows) if r["domain"] == DOMAIN]


def build_disagreement_text(merged: list) -> str:
    out = []
    for r in merged:
        if r["all_agree"]:
            continue
        ind = r["individual_results"]
        votes = {m.split(":")[0]: ind[i]["label"] for i, m in enumerate(JUDGE_MODELS)}
        quotes = {m.split(":")[0]: (ind[i].get("criterion_quote") or "")[:150] for i, m in enumerate(JUDGE_MODELS)}
        out.append(f"Transcript (idx {r['transcript_index']}):\n{r['transcript'][:300]}\n"
                   f"Votes: {votes}\nCriterion quotes cited: {quotes}\n---")
    return "\n".join(out)


def build_alt_a_prompt(v0_rubric: dict, disagreement_text: str) -> str:
    return f"""You are revising an annotation rubric used by three LLM judges to label \
YouTube transcripts as HIGH or LOW signal in the {DOMAIN} domain.

CURRENT RUBRIC:
Domain context: {v0_rubric['domain_context']}
HIGH criteria: {json.dumps(v0_rubric['HIGH'])}
LOW criteria: {json.dumps(v0_rubric['LOW'])}
Conflict rule: {v0_rubric['conflict_rule']}

Below are the specific transcripts where the three judges disagreed under this rubric, \
along with each judge's vote and which criterion they cited as decisive.

{disagreement_text}

Propose a revised rubric that would reduce this disagreement. Make surgical, targeted \
changes to the specific criteria implicated by the disagreements above -- do not rewrite \
criteria that are not implicated.

Respond with ONLY this JSON, nothing else:
{{
  "updated_HIGH": ["criterion 1", "criterion 2", "..."],
  "updated_LOW": ["criterion 1", "criterion 2", "..."],
  "updated_conflict_rule": "...",
  "reasoning": "brief explanation"
}}"""


def build_alt_b_prompt(v0_rubric: dict) -> str:
    return f"""You are revising an annotation rubric used by three LLM judges to label \
YouTube transcripts as HIGH or LOW signal in the {DOMAIN} domain.

CURRENT RUBRIC:
Domain context: {v0_rubric['domain_context']}
HIGH criteria: {json.dumps(v0_rubric['HIGH'])}
LOW criteria: {json.dumps(v0_rubric['LOW'])}
Conflict rule: {v0_rubric['conflict_rule']}

You do NOT have access to any specific disagreement cases or transcripts. Based only on \
reading this rubric itself, propose a revision that makes the criteria more precise and \
less ambiguous for an LLM judge to apply consistently -- e.g. tightening vague language, \
adding concrete examples, or clarifying edge cases you anticipate could be read differently \
by different models.

Respond with ONLY this JSON, nothing else:
{{
  "updated_HIGH": ["criterion 1", "criterion 2", "..."],
  "updated_LOW": ["criterion 1", "criterion 2", "..."],
  "updated_conflict_rule": "...",
  "reasoning": "brief explanation"
}}"""


def call_alt_revision(client: OpenAI, prompt: str) -> dict:
    r = client.chat.completions.create(
        model=ALT_MODEL,
        messages=[{"role": "user", "content": prompt}],
        max_completion_tokens=2000,
    )
    text = r.choices[0].message.content.strip()
    if "```" in text:
        text = text.split("```")[1]
        if text.startswith("json"):
            text = text[4:]
    return json.loads(text.strip())


def run_panel(cache: JudgeCallCache, run_tag: str, rubric_version: str, transcripts: list, rubric: dict) -> list:
    results_by_model = {}
    for model in JUDGE_MODELS:
        per_t = []
        for t in transcripts:
            r = cache.get_or_call(judge_transcript, run_tag, DOMAIN, rubric_version,
                                   t["index"], t["transcript"], rubric, model)
            r["transcript_index"] = t["index"]
            per_t.append(r)
        results_by_model[model] = per_t
    return merge_model_results(transcripts, results_by_model)


def main():
    load_env()
    client = OpenAI()

    transcripts = load_domain_transcripts()
    assert len(transcripts) == 20

    with open(V0_RUBRICS_PATH, encoding="utf-8") as f:
        v0_rubric = json.load(f)[DOMAIN]
    with open(FINAL_RUBRICS_PATH, encoding="utf-8") as f:
        final_rubric = json.load(f)[DOMAIN]

    cache = JudgeCallCache(CACHE_PATH)

    print("Step 1: regenerating v0-iteration disagreement cases for tech_ai (20 transcripts)...")
    merged_v0 = run_panel(cache, "a5_v0_regen", "v0", transcripts, v0_rubric)
    v0_rows = [[r["individual_results"][i]["label"] for i in range(3)] for r in merged_v0]
    v0_metrics = fleiss_style_metrics(v0_rows)
    print(f"  v0 regenerated: weighted={v0_metrics['weighted']:.3f} "
          f"(original run reported 76.7% at iteration 1 -- compare for drift)")

    n_disagreements = sum(1 for r in merged_v0 if not r["all_agree"])
    disagreement_text = build_disagreement_text(merged_v0)
    print(f"  {n_disagreements}/20 disagreement cases recovered")

    print("\nStep 2: generating 2 alternative revisions via gpt-5.6-sol...")
    alt_a_prompt = build_alt_a_prompt(v0_rubric, disagreement_text)
    alt_a_json = call_alt_revision(client, alt_a_prompt)
    alt_a_rubric = {
        "version": "alt_a_disagreement_informed",
        "domain_context": v0_rubric["domain_context"],
        "HIGH": alt_a_json["updated_HIGH"],
        "LOW": alt_a_json["updated_LOW"],
        "conflict_rule": alt_a_json["updated_conflict_rule"],
    }
    print("  alt (a) disagreement-informed: generated")

    alt_b_prompt = build_alt_b_prompt(v0_rubric)
    alt_b_json = call_alt_revision(client, alt_b_prompt)
    alt_b_rubric = {
        "version": "alt_b_rubric_only",
        "domain_context": v0_rubric["domain_context"],
        "HIGH": alt_b_json["updated_HIGH"],
        "LOW": alt_b_json["updated_LOW"],
        "conflict_rule": alt_b_json["updated_conflict_rule"],
    }
    print("  alt (b) rubric-only: generated")

    print("\nStep 3: running both alternatives through the local panel (20 transcripts each)...")
    merged_alt_a = run_panel(cache, "a5_alt_a", "alt_a", transcripts, alt_a_rubric)
    alt_a_rows = [[r["individual_results"][i]["label"] for i in range(3)] for r in merged_alt_a]
    alt_a_metrics = fleiss_style_metrics(alt_a_rows)
    print(f"  alt (a): weighted={alt_a_metrics['weighted']:.3f}")

    merged_alt_b = run_panel(cache, "a5_alt_b", "alt_b", transcripts, alt_b_rubric)
    alt_b_rows = [[r["individual_results"][i]["label"] for i in range(3)] for r in merged_alt_b]
    alt_b_metrics = fleiss_style_metrics(alt_b_rows)
    print(f"  alt (b): weighted={alt_b_metrics['weighted']:.3f}")
    cache.close()

    with open(CALIBRATED_LABELS, encoding="utf-8") as f:
        orig_v1_rows = [[r["llama_label"], r["mistral_label"], r["qwen_label"]]
                         for r in csv.DictReader(f) if r["domain"] == DOMAIN]
    orig_v1_metrics = fleiss_style_metrics(orig_v1_rows)

    prompt_template = build_alt_a_prompt(v0_rubric, "PLACEHOLDER") + build_alt_b_prompt(v0_rubric)
    provenance = record_provenance(
        models=JUDGE_MODELS + [ALT_MODEL],
        dataset_paths=[REVIEW_QUEUE],
        rubric_paths=[V0_RUBRICS_PATH, FINAL_RUBRICS_PATH],
        prompt_template=prompt_template,
        repo_dir=BASE,
    )

    results = {
        "experiment": "A5 -- revision-sensitivity analysis (NOT a controlled causal ablation)",
        "domain": DOMAIN,
        "coordinator_substitution_disclosure": (
            "No ANTHROPIC_API_KEY available; both alternative revisions generated by gpt-5.6-sol "
            "instead of Claude Sonnet (the original coordinator model). This is a genuine confound: "
            "differences from the original coordinator's v1 rubric may partly reflect model-family "
            "differences rather than purely the evidence-visibility manipulation this analysis targets."
        ),
        "v0_regenerated": {
            "metrics": v0_metrics,
            "n_disagreement_cases_recovered": n_disagreements,
            "original_run_reported_v0": 0.767,
            "drift_note": "Regenerated via fresh deterministic (temp=0.0) calls under the same v0 "
                           "rubric; compare to the original run's reported 76.7% to gauge model drift "
                           "since the original calibration run.",
        },
        "conditions": {
            "v0_baseline": v0_metrics,
            "original_coordinator_v1": orig_v1_metrics,
            "alt_a_disagreement_informed": alt_a_metrics,
            "alt_b_rubric_only": alt_b_metrics,
        },
        "alternative_rubrics_generated": {
            "alt_a_disagreement_informed": alt_a_rubric,
            "alt_b_rubric_only": alt_b_rubric,
        },
        "interpretation_guardrails": (
            "Comparison of (a) vs (b) tests whether seeing disagreement evidence adds value beyond "
            "having the rubric alone. Comparison of original-coordinator vs (a) tests whether the "
            "coordinator's specific diagnostic reasoning outperforms a generic revision given the "
            "same evidence, SUBJECT TO the model-substitution confound disclosed above. Named and "
            "interpreted as a sensitivity analysis, not a controlled causal ablation."
        ),
        "provenance": provenance,
    }

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)

    print(f"\n{'='*60}")
    print(f"v0 baseline:              {v0_metrics['weighted']:.3f}")
    print(f"original coordinator v1:  {orig_v1_metrics['weighted']:.3f}")
    print(f"alt (a) disagreement-inf: {alt_a_metrics['weighted']:.3f}")
    print(f"alt (b) rubric-only:      {alt_b_metrics['weighted']:.3f}")
    print(f"\nSaved to {OUT_PATH}")


if __name__ == "__main__":
    main()
